#!/usr/bin/env tcsh

#
# Copyright (c) 2015 Michael Tuexen
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#

set packetdrill = /home/tuexen/packetdrill/gtests/net/packetdrill/packetdrill
set delay = 1
set testcases = (sctp-as-tests/sctp-as-v-1-1-1  \
                 sctp-as-tests/sctp-as-v-1-1-2  \
                 sctp-as-tests/sctp-as-i-1-2-1  \
                 sctp-as-tests/sctp-as-i-1-2-2  \
                 sctp-as-tests/sctp-as-i-1-3-1  \
                 sctp-as-tests/sctp-as-i-1-3-2  \
                 sctp-as-tests/sctp-as-i-1-4    \
                 sctp-as-tests/sctp-as-v-1-5-1  \
                 sctp-as-tests/sctp-as-v-1-5-1  \
                 sctp-as-tests/sctp-as-i-1-2    \
                 sctp-as-tests/sctp-as-v-1-6-1  \
                 sctp-as-tests/sctp-as-v-1-6-2  \
                 sctp-as-tests/sctp-as-v-1-7-1  \
                 sctp-as-tests/sctp-as-i-1-7-2  \
                 sctp-as-tests/sctp-as-v-1-7-3  \
                 sctp-as-tests/sctp-as-i-1-7-4  \
                 sctp-as-tests/sctp-as-v-1-7-5  \
                 sctp-as-tests/sctp-as-i-1-8-1  \
                 sctp-as-tests/sctp-as-i-1-8-2  \
                 sctp-as-tests/sctp-as-i-1-8-3  \
                 sctp-as-tests/sctp-as-i-1-8-4  \
                 sctp-as-tests/sctp-as-o-1-9-1  \
                 sctp-as-tests/sctp-as-o-1-9-2  \
                 sctp-as-tests/sctp-as-v-1-10-1 \
                 sctp-as-tests/sctp-as-v-1-10-2 \
                 sctp-as-tests/sctp-as-v-1-11-1 \
                 sctp-as-tests/sctp-as-v-1-11-2 \
                 sctp-as-tests/sctp-as-v-1-12-1 \
                 sctp-as-tests/sctp-as-i-1-12-2 \
                 sctp-as-tests/sctp-as-v-1-13-1 \
                 sctp-as-tests/sctp-as-i-1-13-2 \
                 sctp-as-tests/sctp-as-i-1-14-1 \
                 sctp-as-tests/sctp-as-i-1-14-2 \
                 sctp-as-tests/sctp-as-i-1-15   \
                 sctp-at-tests/sctp-at-v-2-2    \
                 sctp-at-tests/sctp-at-i-2-3    \
                 sctp-at-tests/sctp-at-i-2-4    \
                 sctp-at-tests/sctp-at-i-2-5    \
                 sctp-at-tests/sctp-at-v-2-6    \
                 sctp-at-tests/sctp-at-i-2-7-1  \
                 sctp-at-tests/sctp-at-i-2-7-2  \
                 sctp-at-tests/sctp-at-i-2-7-3  \
                 sctp-at-tests/sctp-at-i-2-7-4  \
                 sctp-at-tests/sctp-at-i-2-8    \
                 sctp-at-tests/sctp-at-i-2-9    \
                 sctp-at-tests/sctp-at-i-2-10   \
                 sctp-at-tests/sctp-at-i-2-11   \
                 sctp-at-tests/sctp-at-i-2-12   \
                 sctp-at-tests/sctp-at-i-2-13   \
                 sctp-at-tests/sctp-at-v-2-14   \
                 sctp-imh-tests/sctp-imh-i-3-1  \
                 sctp-imh-tests/sctp-imh-i-3-2  \
                 sctp-imh-tests/sctp-imh-i-3-3  \
                 sctp-imh-tests/sctp-imh-i-3-4  \
                 sctp-imh-tests/sctp-imh-i-3-5  \
                 sctp-imh-tests/sctp-imh-i-3-6  \
                 sctp-imh-tests/sctp-imh-i-3-7  \
                 sctp-imh-tests/sctp-imh-i-3-8  \
                 sctp-imh-tests/sctp-imh-i-3-9  \
                 sctp-imh-tests/sctp-imh-i-3-10 \
                 sctp-dm-tests/sctp-dm-o-4-1    \
                 sctp-dm-tests/sctp-dm-o-4-2-1  \
                 sctp-dm-tests/sctp-dm-o-4-2-2  \
                 sctp-dm-tests/sctp-dm-o-4-3    \
                 sctp-dm-tests/sctp-dm-o-4-4    \
                 sctp-dm-tests/sctp-dm-o-4-5    \
                 sctp-dm-tests/sctp-dm-o-4-6-1  \
                 sctp-dm-tests/sctp-dm-o-4-6-2  \
                 sctp-dm-tests/sctp-dm-o-4-6-3  \
                 sctp-dm-tests/sctp-dm-o-4-7-1  \
                 sctp-dm-tests/sctp-dm-o-4-7-2  \
                 sctp-dm-tests/sctp-dm-o-4-7-3  \
                 sctp-dm-tests/sctp-dm-o-4-8    \
                 sctp-dm-tests/sctp-dm-o-4-9    \
                 sctp-dm-tests/sctp-dm-o-4-10   \
                 sctp-fh-tests/sctp-fh-i-5-1-1  \
                 sctp-fh-tests/sctp-fh-i-5-1-2  \
                 sctp-fh-tests/sctp-fh-v-5-2    \
                 sctp-fh-tests/sctp-fh-o-5-3-1  \
                 sctp-fh-tests/sctp-fh-o-5-3-2  \
                 sctp-fh-tests/sctp-fh-o-5-3-3  \
                 sctp-fh-tests/sctp-fh-o-5-3-4  \
                 sctp-fh-tests/sctp-fh-o-5-3-5  \
                 sctp-e-tests/sctp-e-o-6-1      \
                 sctp-e-tests/sctp-e-o-6-2      \
                 sctp-e-tests/sctp-e-i-6-3      \
                 sctp-e-tests/sctp-e-i-6-4      \
                 sctp-e-tests/sctp-e-i-6-5      \
                 sctp-e-tests/sctp-e-i-6-6      \
                 sctp-bdc-tests/sctp-bdc-i-7-1  \
                 sctp-bdc-tests/sctp-bdc-i-7-2  \
                 sctp-bdc-tests/sctp-bdc-i-7-3  \
                 sctp-bdc-tests/sctp-bdc-v-7-4  \
                 sctp-bdc-tests/sctp-bdc-v-7-5  \
                 sctp-bdc-tests/sctp-bdc-v-7-6  \
                 sctp-bdc-tests/sctp-bdc-v-7-7  \
                 sctp-bdc-tests/sctp-bdc-v-7-8  \
                 sctp-d-tests/sctp-d-v-8-1      \
                 sctp-d-tests/sctp-d-v-8-2      \
                 sctp-d-tests/sctp-d-v-8-3      \
                 sctp-d-tests/sctp-d-v-8-4      \
                 sctp-d-tests/sctp-d-i-8-5      \
                 sctp-d-tests/sctp-d-o-8-6      \
                 sctp-d-tests/sctp-d-o-8-7      \
                 sctp-d-tests/sctp-d-o-8-8      \
                 sctp-d-tests/sctp-d-v-8-9      \
                 sctp-d-tests/sctp-d-v-8-10     \
                 sctp-d-tests/sctp-d-i-8-11     \
                 sctp-d-tests/sctp-d-o-8-12     \
                 sctp-d-tests/sctp-d-v-8-13     \
                 sctp-d-tests/sctp-d-v-8-14     \
                 sctp-d-tests/sctp-d-v-8-15     \
                 sctp-a-tests/sctp-a-v-9-1      \
                 sctp-a-tests/sctp-a-v-9-2      \
                 sctp-a-tests/sctp-a-o-9-3      \
                 sctp-m-tests/sctp-m-i-10-1     \
                 sctp-m-tests/sctp-m-i-10-2     \
                 sctp-m-tests/sctp-m-i-10-3     \
                 sctp-m-tests/sctp-m-i-10-4     \
                 sctp-rt-tests/sctp-rt-i-11-1   \
                 sctp-rt-tests/sctp-rt-i-11-2   \
                 sctp-rt-tests/sctp-rt-i-11-3   )

set rootdir = `/usr/bin/dirname $0`
set os = `uname -s | tr '[A-Z]' '[a-z]'`
set passed = 0
set failed = 0
set run = 0
set skipped = 0

printf "Name                                        Verdict\n"
printf "===================================================\n"
foreach testcase ($testcases)
  printf "%-40.40s " $testcase
  if (-f ${rootdir}/${testcase}-$os.pkt) then
    $packetdrill ${rootdir}/${testcase}-$os.pkt >& /dev/null
    set result = $status
    set found = 1
  else if (-f ${rootdir}/${testcase}.pkt) then
    $packetdrill ${rootdir}/${testcase}.pkt >& /dev/null
    set result = $status
    set found = 1
  else
    set found = 0
  endif
  if ($found == 1) then
    if ($result == 0) then
      @ passed++
      printf "\033[32m%10s\033[0m\n" "PASSED"
    else
      @ failed++
      printf "\033[31m%10s\033[0m\n" "FAILED"
    endif
    @ run++
  else
    printf "\033[34m%10s\033[0m\n" "SKIPPED"
    @ skipped++
  endif

  sleep $delay
end
printf "===================================================\n"
printf "Summary: Number of tests run:     %3u\n" $run
printf "         Number of tests passed:  %3u\n" $passed
printf "         Number of tests failed:  %3u\n" $failed
printf "         Number of tests skipped: %3u\n" $skipped
